# -*- coding: utf-8 -*-
"""AI_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L12rShQCQ8KcVseNEmM203Oal2ttwN1N
"""

import heapq

class Node:
    def __init__(self, name, cost=0, heuristic=0, parent=None):
        self.name = name
        self.cost = cost  # Actual cost to reach this node from start
        self.heuristic = heuristic  # Heuristic estimated cost to goal
        self.parent = parent  # Parent node to track the path

    def __lt__(self, other):
        return (self.cost + self.heuristic) < (other.cost + other.heuristic)

def heuristic(node, goal):
    # Simple heuristic: difference in node names (could be adjusted based on actual problem)
    heuristic_map = {
        'A': 6, 'B': 5, 'C': 4, 'D': 3, 'E': 2, 'F': 1, 'G': 0
    }
    return heuristic_map.get(node.name, float('inf'))

def a_star_algorithm(graph, start_name, goal_name):
    # Initialize the start and goal nodes
    start_node = Node(start_name, cost=0, heuristic=heuristic(Node(start_name), Node(goal_name)))
    goal_node = Node(goal_name)

    # Priority queue (open set)
    open_set = []
    heapq.heappush(open_set, start_node)

    # Closed set (visited nodes)
    closed_set = set()

    # Dictionary to store the shortest path
    came_from = {}

    while open_set:
        # Get the node with the lowest f = cost + heuristic
        current_node = heapq.heappop(open_set)

        # If we reached the goal, reconstruct the path
        if current_node.name == goal_name:
            path = []
            while current_node:
                path.append(current_node.name)
                current_node = current_node.parent
            return path[::-1]  # Return path in correct order

        closed_set.add(current_node.name)

        # Explore neighbors
        for neighbor, cost in graph[current_node.name].items():
            if neighbor in closed_set:
                continue

            # Calculate the cost and heuristic for the neighbor
            tentative_cost = current_node.cost + cost
            neighbor_node = Node(neighbor, cost=tentative_cost, heuristic=heuristic(Node(neighbor), goal_node), parent=current_node)

            # Add neighbor to open set
            heapq.heappush(open_set, neighbor_node)

    return None  # No path found

# Graph representation as an adjacency list
graph = {
    'A': {'B': 1, 'C': 5},
    'B': {'A': 1, 'C': 5, 'D': 5},
    'C': {'A': 4, 'B': 2, 'E': 3},
    'D': {'B': 5, 'F': 2},
    'E': {'C': 5, 'F': 1},
    'F': {'D': 2, 'E': 1, 'G': 2},
    'G': {'F': 2}
}

# Run A* to find the shortest path from A to G
path = a_star_algorithm(graph, 'A', 'G')

if path:
    print("Shortest path:", path)
else:
    print("No path found.")