# -*- coding: utf-8 -*-
"""MFCS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ct4bijkJcxMb6q6WJSTIA1DqdqSy-1ef
"""

import numpy as np
import matplotlib.pyplot as plt

# Probability distribution for a 6-sided fair dice
sides = 6
probabilities = np.array([1/sides] * sides)
outcomes = np.arange(1, sides + 1)

# Compute mean and variance
mean = np.sum(outcomes * probabilities)
variance = np.sum(((outcomes - mean) ** 2) * probabilities)

print(f"Mean of the dice: {mean}")
print(f"Variance of the dice: {variance}")

# Sum of two dice throws, thrown twice (4 dice rolls in total)
possible_sums = np.arange(4, 4 * sides + 1)

# Probability mass function (PMF) for the sum of four dice
pmf = np.zeros(len(possible_sums))
for i in range(1, sides + 1):
    for j in range(1, sides + 1):
        for k in range(1, sides + 1):
            for l in range(1, sides + 1):
                total_sum = i + j + k + l
                pmf[total_sum - 4] += 1 / (sides ** 4)

# Plot the PMF
plt.figure(figsize=(10, 6))
plt.bar(possible_sums, pmf, color='skyblue', edgecolor='black')
plt.title('Probability Mass Function (PMF) for the Sum of Four Dice', fontsize=14)
plt.xlabel('Sum of Four Dice', fontsize=12)
plt.ylabel('Probability', fontsize=12)
plt.xticks(possible_sums)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

#For 2 Dices
# Sum of two dice throws
sums = np.arange(2, 2 * sides + 1)

# Probability mass function (PMF) for the sum of two dice
pmf = np.zeros(len(sums))
for i in range(1, sides + 1):
    for j in range(1, sides + 1):
        pmf[i + j - 2] += 1 / (sides ** 2)

# Plot the PMF
plt.figure(figsize=(10, 6))
plt.bar(sums, pmf, color='skyblue', edgecolor='black')
plt.title('Probability Mass Function (PMF) for the Sum of Two Dice', fontsize=14)
plt.xlabel('Sum of Two Dice', fontsize=12)
plt.ylabel('Probability', fontsize=12)
plt.xticks(sums)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()