# -*- coding: utf-8 -*-
"""MFCS4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMAQ4UFb1RFcyT8nSA8H0QVaqcgurWEs
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

data = pd.read_csv('/tvmarketing.csv')

#Explore Data
print(data.head())

print(data.isnull().sum())

#Define Features and Target Variable:
X = data[['TV']]  # Feature: TV marketing expenses
y = data['Sales']  # Target: Sales

#plit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Initialize and Train the Linear Regression Model:
model = LinearRegression()
model.fit(X_train, y_train)

#Make Predictions on the Test Set:
y_pred = model.predict(X_test)

#Evaluating the Model:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

# Visualizing the Results:
plt.scatter(X_test, y_test, color='blue', label='Actual Sales')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Predicted Sales')
plt.xlabel('TV Marketing Expenses')
plt.ylabel('Sales')
plt.title('TV Marketing Expenses vs. Sales')
plt.legend()
plt.show()