# -*- coding: utf-8 -*-
"""MFCS3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCPK0fhmDTohDITN3YMePAaRGQJZpLUc
"""

import numpy as np

class HiddenMarkovModel:
    def __init__(self, states, observations, start_prob, trans_prob, emiss_prob):
        self.states = states
        self.observations = observations
        self.start_prob = start_prob
        self.trans_prob = trans_prob
        self.emiss_prob = emiss_prob

    def generate_sequence(self, length):
        state_sequence = []
        observation_sequence = []

        # Choose initial state
        current_state = np.random.choice(self.states, p=self.start_prob)
        state_sequence.append(current_state)

        # Generate initial observation
        obs_index = np.random.choice(len(self.observations), p=self.emiss_prob[self.states.index(current_state)])
        observation_sequence.append(self.observations[obs_index])

        # Generate subsequent states and observations
        for _ in range(1, length):
            current_state_index = self.states.index(current_state)

            # Transition to the next state
            current_state = np.random.choice(self.states, p=self.trans_prob[current_state_index])
            state_sequence.append(current_state)

            # Generate observation from the current state
            obs_index = np.random.choice(len(self.observations), p=self.emiss_prob[self.states.index(current_state)])
            observation_sequence.append(self.observations[obs_index])

        return state_sequence, observation_sequence

# Define states and observations
states = ["Noun", "Verb", "Adjective"]
observations = ["dog", "runs", "fast", "cat", "jumps", "lazy"]

# Define probabilities
start_prob = [0.5, 0.3, 0.2]  # Initial probabilities for states

# Transition probabilities: states -> states
trans_prob = [
    [0.3, 0.4, 0.3],  # Noun -> [Noun, Verb, Adjective]
    [0.2, 0.5, 0.3],  # Verb -> [Noun, Verb, Adjective]
    [0.4, 0.4, 0.2],  # Adjective -> [Noun, Verb, Adjective]
]

# Emission probabilities: states -> observations
emiss_prob = [
    [0.5, 0.1, 0.1, 0.3, 0.0, 0.0],  # Noun -> [dog, runs, fast, cat, jumps, lazy]
    [0.0, 0.6, 0.0, 0.0, 0.4, 0.0],  # Verb -> [dog, runs, fast, cat, jumps, lazy]
    [0.0, 0.0, 0.5, 0.0, 0.0, 0.5],  # Adjective -> [dog, runs, fast, cat, jumps, lazy]
]

# Create HMM
hmm = HiddenMarkovModel(states, observations, start_prob, trans_prob, emiss_prob)

# Generate sequences
num_words = 10
state_seq, obs_seq = hmm.generate_sequence(num_words)

# Display results
print("Generated State Sequence:", state_seq)
print("Generated Observation Sequence:", " ".join(obs_seq))